In [44]:
import numpy as np
import math
import pythonXLL
import luxpy as lx
#import MCToolsPTBVMe

trials = 100
number = 0
wl = lx.getwlr([360, 830, 5])

In [2]:
SPDX = %xl_get -c _SPD2

In [3]:
SPDX.shape

(95, 2)

In [4]:
SPD=SPDX.to_numpy()[:,0]

In [5]:
SPD

array([6.1495e-02, 6.9526e-02, 7.8271e-02, 8.7760e-02, 9.8018e-02,
       1.0907e-01, 1.2093e-01, 1.3362e-01, 1.4717e-01, 1.6157e-01,
       1.7685e-01, 1.9300e-01, 2.1005e-01, 2.2799e-01, 2.4682e-01,
       2.6654e-01, 2.8714e-01, 3.0862e-01, 3.3098e-01, 3.5419e-01,
       3.7824e-01, 4.0312e-01, 4.2881e-01, 4.5529e-01, 4.8254e-01,
       5.1053e-01, 5.3924e-01, 5.6865e-01, 5.9871e-01, 6.2942e-01,
       6.6073e-01, 6.9261e-01, 7.2504e-01, 7.5798e-01, 7.9139e-01,
       8.2525e-01, 8.5952e-01, 8.9416e-01, 9.2914e-01, 9.6444e-01,
       1.0000e+00, 1.0358e+00, 1.0718e+00, 1.1080e+00, 1.1443e+00,
       1.1807e+00, 1.2172e+00, 1.2538e+00, 1.2903e+00, 1.3268e+00,
       1.3633e+00, 1.3997e+00, 1.4360e+00, 1.4721e+00, 1.5081e+00,
       1.5439e+00, 1.5795e+00, 1.6149e+00, 1.6499e+00, 1.6848e+00,
       1.7193e+00, 1.7534e+00, 1.7873e+00, 1.8207e+00, 1.8538e+00,
       1.8865e+00, 1.9188e+00, 1.9506e+00, 1.9820e+00, 2.0130e+00,
       2.0435e+00, 2.0735e+00, 2.1030e+00, 2.1320e+00, 2.1605e

In [6]:
SPD.shape

(95,)

In [7]:
uSPD=SPDX.to_numpy()[:,1]

In [8]:
uSPD

array([1.0000e-02, 1.0000e-02, 1.0000e-02, 1.0000e-02, 1.0000e-02,
       1.0000e-02, 1.0000e-02, 1.0000e-02, 1.0000e-02, 1.0000e-02,
       1.0000e-02, 1.0000e-02, 1.0000e-02, 1.0000e-02, 1.0000e-02,
       1.0000e-02, 1.0000e-02, 1.0000e-02, 1.0000e-02, 1.0000e-02,
       1.0000e-02, 1.0000e-02, 1.0000e-02, 1.0000e-02, 1.0000e-02,
       1.0000e-02, 1.0000e-02, 1.0000e-02, 1.0000e-02, 1.0000e-02,
       1.0000e-02, 1.0000e-02, 1.0000e-02, 1.0000e-02, 1.0000e-02,
       1.0000e-02, 1.0000e-02, 1.0000e-02, 1.0000e-02, 1.0000e-02,
       1.0000e-02, 1.0000e-02, 1.0000e-02, 1.0000e-02, 1.0000e-02,
       1.0000e-02, 1.0000e-02, 1.0000e-02, 1.0000e-02, 1.0000e-02,
       1.0000e-02, 1.0000e-02, 1.0000e-02, 1.0000e-02, 1.0000e-02,
       1.0000e-02, 1.0000e-02, 1.0000e-02, 1.0000e-02, 1.0000e-02,
       1.0000e-02, 1.0000e-02, 1.0000e-02, 1.0000e-02, 1.0000e-02,
       1.0000e-02, 1.0000e-02, 1.0000e-02, 1.0000e-02, 1.0000e-02,
       1.0000e-02, 1.0000e-02, 1.0000e-02, 1.0000e-02, 1.0000e

In [9]:
wl.shape

(95,)

In [10]:
rMatrix = np.zeros((trials,wl.size))

In [11]:
rMatrix.shape

(100, 95)

In [12]:
rMatrixSPD = np.zeros((trials,wl.size))

In [13]:
rGammai = np.random.normal(size=(trials, number+1))
rGammai

array([[-1.8884e+00],
       [1.6747e-01],
       [1.2001e+00],
       [5.6893e-01],
       [9.9973e-01],
       [-4.2835e-01],
       [2.1993e-01],
       [1.0476e+00],
       [-8.6668e-01],
       [-1.8899e-01],
       [-4.5078e-01],
       [-1.6532e-01],
       [-1.0431e+00],
       [4.1748e-01],
       [-1.5988e+00],
       [4.4779e-01],
       [6.0431e-01],
       [-1.0804e+00],
       [1.1287e+00],
       [-5.3196e-01],
       [1.2283e+00],
       [-3.7949e-01],
       [7.4810e-01],
       [-5.6122e-01],
       [2.3412e+00],
       [8.4543e-01],
       [6.3131e-01],
       [1.9164e+00],
       [-1.6670e+00],
       [-1.0181e+00],
       [2.0403e-01],
       [-9.0485e-02],
       [7.4365e-01],
       [6.2811e-01],
       [1.9418e+00],
       [-8.0027e-01],
       [5.4453e-01],
       [9.5466e-01],
       [7.9247e-01],
       [1.7470e+00],
       [-5.6064e-01],
       [-1.7157e+00],
       [-1.1653e+00],
       [3.6518e-01],
       [7.9058e-01],
       [-2.7053e-01],
       [2.1871

In [14]:
%xl_set rGammai -c _Test

In [15]:
rSum = np.sum(rGammai**2, axis=1)
rSum

array([3.5660e+00, 2.8047e-02, 1.4402e+00, 3.2368e-01, 9.9945e-01,
       1.8349e-01, 4.8371e-02, 1.0974e+00, 7.5113e-01, 3.5718e-02,
       2.0320e-01, 2.7331e-02, 1.0880e+00, 1.7429e-01, 2.5562e+00,
       2.0052e-01, 3.6519e-01, 1.1673e+00, 1.2740e+00, 2.8298e-01,
       1.5088e+00, 1.4401e-01, 5.5965e-01, 3.1497e-01, 5.4813e+00,
       7.1475e-01, 3.9855e-01, 3.6727e+00, 2.7789e+00, 1.0364e+00,
       4.1626e-02, 8.1875e-03, 5.5302e-01, 3.9452e-01, 3.7707e+00,
       6.4044e-01, 2.9652e-01, 9.1138e-01, 6.2800e-01, 3.0518e+00,
       3.1431e-01, 2.9436e+00, 1.3579e+00, 1.3336e-01, 6.2501e-01,
       7.3184e-02, 4.7834e-02, 8.2113e-01, 7.3215e-02, 1.1614e+00,
       1.9187e+00, 2.0883e-01, 1.9204e+00, 1.2989e-02, 4.8384e-01,
       3.0585e+00, 6.6763e-02, 1.3336e+00, 8.0078e-01, 1.0456e+00,
       2.4207e-01, 3.7152e+00, 7.1824e-03, 6.4690e-01, 1.1407e+00,
       1.7681e-02, 7.6432e-01, 1.6779e-01, 4.4520e+00, 2.5314e+00,
       1.9495e-01, 3.2118e+00, 1.8866e+00, 8.1089e-01, 2.1120e

In [16]:
outSum = rSum
outSum.resize(trials,1)
%xl_set outSum -c _Test2

rSum

In [17]:
rSum2 = np.sqrt(np.sum(rGammai**2, axis=1))
rSum2

array([1.8884e+00, 1.6747e-01, 1.2001e+00, 5.6893e-01, 9.9973e-01,
       4.2835e-01, 2.1993e-01, 1.0476e+00, 8.6668e-01, 1.8899e-01,
       4.5078e-01, 1.6532e-01, 1.0431e+00, 4.1748e-01, 1.5988e+00,
       4.4779e-01, 6.0431e-01, 1.0804e+00, 1.1287e+00, 5.3196e-01,
       1.2283e+00, 3.7949e-01, 7.4810e-01, 5.6122e-01, 2.3412e+00,
       8.4543e-01, 6.3131e-01, 1.9164e+00, 1.6670e+00, 1.0181e+00,
       2.0403e-01, 9.0485e-02, 7.4365e-01, 6.2811e-01, 1.9418e+00,
       8.0027e-01, 5.4453e-01, 9.5466e-01, 7.9247e-01, 1.7470e+00,
       5.6064e-01, 1.7157e+00, 1.1653e+00, 3.6518e-01, 7.9058e-01,
       2.7053e-01, 2.1871e-01, 9.0616e-01, 2.7058e-01, 1.0777e+00,
       1.3852e+00, 4.5698e-01, 1.3858e+00, 1.1397e-01, 6.9559e-01,
       1.7489e+00, 2.5839e-01, 1.1548e+00, 8.9486e-01, 1.0225e+00,
       4.9201e-01, 1.9275e+00, 8.4749e-02, 8.0430e-01, 1.0680e+00,
       1.3297e-01, 8.7426e-01, 4.0962e-01, 2.1100e+00, 1.5910e+00,
       4.4153e-01, 1.7921e+00, 1.3735e+00, 9.0049e-01, 4.5956e

In [18]:
rSum2.shape

(100,)

In [19]:
outSum = rSum2
outSum.resize(trials,1)
%xl_set outSum -c _Test3

In [20]:
rGammai.shape

(100, 1)

In [21]:
rSum2.shape

(100, 1)

In [22]:
rGammaiN = rGammai/rSum2
rGammaiN.shape

(100, 1)

No normalization for the fully correlated part

In [27]:
rGammaiN[:,0] = rGammai[:,0]

In [26]:
%xl_set rGammaiN -c _Test4

In [27]:
rPhasei = np.random.uniform(low = 0, high = 2*math.pi, size = (trials,number+1))

In [28]:
rPhasei.shape

(100, 11)

In [29]:
def py_getBaseFunctions( number, wl, phaseVector):
    lambda1 = wl[0]
    deltaLambda = wl[wl.size-1]-lambda1
    baseFunctions = np.zeros((number+1, wl.size))
    for i in range(number+1):
        if i==0:
            singleBase = np.ones(wl.size)
        else:
            singleBase = math.sqrt(2)*np.sin(i*(2*math.pi*((wl-lambda1)/(deltaLambda))+phaseVector[i]))
        baseFunctions[i,:] = singleBase.transpose()
    return baseFunctions.transpose()

In [30]:
 for i in range(trials):
    baseFunctions = py_getBaseFunctions( number, wl, rPhasei[i])
    deltaSPD = np.dot(baseFunctions, rGammaiN[i].T)
    rMatrix[i] = deltaSPD.T
    rMatrixSPD[i] = (1.+rMatrix[i]*uSPD)*SPD


In [31]:
baseFunctions.shape

(95, 11)

In [32]:
rGammaiN.T.shape

(11, 100)

In [33]:
rGammaiN[0]

array([3.9067e-01, 2.5998e-01, 5.0389e-01, 1.7267e-01, -1.2625e-03,
       2.8277e-02, -2.7644e-01, 5.5198e-01, -5.6025e-02, 2.9056e-02,
       -3.3194e-01])

In [34]:
deltaSPD.shape

(95,)

In [35]:
rMatrix.shape

(100, 95)

In [36]:
%xl_set baseFunctions -c _SpecTest1

In [37]:
deltaSPDTemp =  deltaSPD
deltaSPDTemp.resize((wl.size,1)) 
deltaSPDTemp.shape
%xl_set deltaSPDTemp -c _SpecTest2

In [38]:
%xl_set rMatrix.T -c _SpecTest3

In [39]:
%xl_set rMatrixSPD.T -c _SpecTest4